// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"baize-monitor/internal/server"
	"baize-monitor/internal/server/alert/handler"
	"baize-monitor/internal/server/alert/repository"
	"baize-monitor/internal/server/alert/service"
	"baize-monitor/internal/server/http/routes"
	snmp2 "baize-monitor/internal/server/snmp"
	"baize-monitor/pkg/config"
	"baize-monitor/pkg/snmp"
	storage2 "baize-monitor/pkg/storage"
	"baize-monitor/pkg/storage/postgres"
)

// Injectors from provider.go:

func InitializeServer(serverConfigPath string) (*server.BaiZeServer, error) {
	serverConfig, err := ProvideConfig(serverConfigPath)
	if err != nil {
		return nil, err
	}
	client, err := ProvideDatabase(serverConfig)
	if err != nil {
		return nil, err
	}
	bmcTrapParserRepository := ProvideBMCParserRepository(client)
	bmcTrapParserService := ProvideBMCParserService(bmcTrapParserRepository)
	bmcTrapParserHandler := ProvideBMCParserHandler(bmcTrapParserService)
	adminRouter := ProvideBMCParserRouter(bmcTrapParserHandler)
	adminServer := ProvideAdminServer(serverConfig, adminRouter)
	bmcTrapParserCache := ProviderBMCTrapParserCache(bmcTrapParserRepository)
	alertRepo := ProviderAlterRepository(client)
	bmcTrapService := ProvideBMCTrapService(bmcTrapParserCache, alertRepo)
	bmcTrapHandler := ProvideBMCTrapHandler(bmcTrapService)
	alertRouter := ProvideAlertRouter(bmcTrapHandler)
	alertServer, err := ProvideAlertService(serverConfig, alertRouter)
	if err != nil {
		return nil, err
	}
	distributedLockerInterface, err := ProviderDistributedLocker(serverConfig)
	if err != nil {
		return nil, err
	}
	responseManagerInterface := ProvideResponseManager(serverConfig)
	snmpServer, err := ProvideSNMPServer(serverConfig, distributedLockerInterface, responseManagerInterface)
	if err != nil {
		return nil, err
	}
	baiZeServer := ProviderBaizieServer(serverConfig, adminServer, alertServer, snmpServer)
	return baiZeServer, nil
}

// provider.go:

// ProvideConfig 配置
func ProvideConfig(serverConfigPath string) (*config.ServerConfig, error) {
	return config.LoadServerConfig(serverConfigPath)
}

// ProvideDatabase 数据库
func ProvideDatabase(cfg *config.ServerConfig) (*storage.Client, error) {
	return storage.NewClient(cfg.PostGresConfig)
}

// ProvideBMCParserRepository BMC Repository
func ProvideBMCParserRepository(db *storage.Client) repository.BMCTrapParserRepository {
	return repository.NewBMCTrapParserRepository(db.DB)
}

// ProvideBMCParserService BMC Service
func ProvideBMCParserService(repo repository.BMCTrapParserRepository) service.BMCTrapParserService {
	return service.NewBMCTrapParserServiceImp(repo)
}

// ProvideBMCParserHandler BMC Handler
func ProvideBMCParserHandler(s service.BMCTrapParserService) handler.BMCTrapParserHandler {
	return handler.NewBMCTrapParserHandler(s)
}

func ProvideBMCParserRouter(h handler.BMCTrapParserHandler) routes.AdminRouter {
	return routes.NewAdminRouter(h)
}

func ProvideAdminServer(cfg *config.ServerConfig, r routes.AdminRouter) *server.AdminServer {
	return server.NewAdminServer(cfg, r)
}

func ProviderAlterRepository(db *storage.Client) repository.AlertRepo {
	return repository.NewAlertRepoImp(db.DB)
}

func ProviderBMCTrapParserCache(btpr repository.BMCTrapParserRepository) *service.BMCTrapParserCache {
	return service.NewBMCTrapParserCache(btpr)
}

func ProvideBMCTrapService(parserCache *service.BMCTrapParserCache, alertRepo repository.AlertRepo) service.BMCTrapService {
	return service.NewBMCTrapServiceImp(parserCache, alertRepo)
}

func ProvideBMCTrapHandler(
	bmcTrapService service.BMCTrapService,
) handler.BMCTrapHandler {
	return handler.NewBMCTrapHandler(bmcTrapService)
}

func ProvideAlertRouter(bmcTraprH handler.BMCTrapHandler) routes.AlertRouter {
	return routes.NewAlertRouter(bmcTraprH)
}

func ProvideAlertService(cfg *config.ServerConfig, r routes.AlertRouter) (*server.AlertServer, error) {
	return server.NewAlertServer(cfg, r)
}

func ProviderDistributedLocker(cfg *config.ServerConfig) (storage2.DistributedLockerInterface, error) {
	return storage2.NewRedisDistributedLocker(cfg.RedisConfig)
}

func ProvideResponseManager(cfg *config.ServerConfig) snmp.ResponseManagerInterface {
	return snmp.NewResponseManager(cfg.ResponseManagerConfig)
}

func ProvideSNMPServer(cfg *config.ServerConfig,
	locker storage2.DistributedLockerInterface,
	responseMgr snmp.ResponseManagerInterface,
) (*snmp2.SNMPServer, error) {
	return snmp2.NewSNMPServer(cfg, locker, responseMgr)
}

func ProviderBaizieServer(config2 *config.ServerConfig,
	adminServer *server.AdminServer,
	alertServer *server.AlertServer,
	snmpServer *snmp2.SNMPServer,
) *server.BaiZeServer {
	return server.NewBaiZeServer(config2, adminServer,
		alertServer,
		snmpServer,
	)
}
